//
//  IDCConstants.m
//  iducation
//
//  Created by pebertli on 26/02/13.
//  Copyright (c) 2013 handverse. All rights reserved.
//

#import "IDCConstants.h"

const float WIDTH_IPAD = 768.0;
const float HEIGHT_IPAD = 1024.0;
const float HEIGHT_NOTIFICATION_BAR_IPAD = 20.0;

const int HEIGHT_NOTE_VIEW_IPAD = 350;
const int WIDTH_NOTE_VIEW_IPAD = 350;
const int OFFSET_NOTE_VIEW_IPAD = 70;

const int HEIGHT_INDEX_VIEW_IPAD = 350;
const int WIDTH_INDEX_VIEW_IPAD = 350;

const int X_CENTER_MENU_BUTTON_IPAD = 388;
const int Y_CENTER_MENU_BUTTON_IPAD = 900;

const int X_LIMIT_CENTER_MENU_BUTTON_IPAD = 350;
const int Y_LIMIT_CENTER_MENU_BUTTON_IPAD = 0;

const int X_OFFSET_CENTER_NAVIGATION_BUTTON_IPAD = 100;
const int Y_OFFSET_CENTER_NAVIGATION_BUTTON_IPAD = 10;

const int X_OFFSET_CENTER_INDEX_BUTTON_IPAD = 0;
const int Y_OFFSET_CENTER_INDEX_BUTTON_IPAD = 10;

const int X_OFFSET_CENTER_TEXT_SELECTION_BUTTON_IPAD = 20;
const int Y_OFFSET_CENTER_TEXT_SELECTION_BUTTON_IPAD = 30;

const int WIDTH_NAVIGATION_BUTTON_IPAD = 48;
const int HEIGHT_NAVIGATION_BUTTON_IPAD = 48;

const int X_OFFSET_NAVIGATION_BUTTON_IPAD = 5;

const float VERY_SHORT_TIME_INTERVAL = 0.2;
const float SHORT_TIME_INTERVAL = 0.35;
const float FAIR_TIME_INTERVAL = 0.5;
const float LONG_TIME_INTERVAL = 0.75;

const float RADIUS_CORNER_VIEW = 8;
const int OFFSET_SHADOW_VIEW = 10;
const float RADIUS_SHADOW_VIEW = 8;
const float OPACITY_SHADOW_VIEW = 0.5;

const int HEIGHT_CELL_TABLE_IPAD = 120;

const int SIZE_FONT_NOTE_VIEW_IPAD = 19;
const float OFFSET_BASELINE_NOTE_VIEW_IPAD = 6;
const float OFFSET_LETTER_LINE_NOTE_VIEW_IPAD = 0.5;
const int X_MARGIN_NOTE_VIEW_IPAD = 8;

const int X_MARGIN_POST_IT_IPAD = 735;
const int WIDTH_POST_IT_IPAD = 23;
const int HEIGHT_POST_IT_IPAD = 23;

const int X_MARGIN_MARK_TEXT_IPAD = 4;
const int Y_MARGIN_MARK_TEXT_IPAD = 4;
const int X_RANDOM_RANGE_MARGIN_MARK_TEXT_IPAD = 2;
const int Y_RANDOM_RANGE_MARGIN_MARK_TEXT_IPAD = 2;
const int SLICE_HUMPS_WIDTH_MARK_TEXT_IPAD = 20;
const int SLICE_HUMPS_HEIGHT_MARK_TEXT_IPAD = 50;
const int MINIMUM_HUMPS_WIDTH_MARK_TEXT_IPAD = 5;
const int MINIMUM_HUMPS_HEIGHT_MARK_TEXT_IPAD = 5;
const int X_RANDOM_RANGE_CONTROL_POINT_MARK_TEXT_IPAD = 4;
const int Y_RANDOM_RANGE_CONTROL_POINT_MARK_TEXT_IPAD = 4;

const float R_COLOR_GRADIENT_START_MARK_TEXT_THEME_DEFAULT = 1.0;
const float G_COLOR_GRADIENT_START_MARK_TEXT_THEME_DEFAULT = 0.0;
const float B_COLOR_GRADIENT_START_MARK_TEXT_THEME_DEFAULT = 0.7;
const float A_COLOR_GRADIENT_START_MARK_TEXT_THEME_DEFAULT = 0.8;
const float R_COLOR_GRADIENT_END_MARK_TEXT_THEME_DEFAULT = 0.9;
const float G_COLOR_GRADIENT_END_MARK_TEXT_THEME_DEFAULT = 0.0;
const float B_COLOR_GRADIENT_END_MARK_TEXT_THEME_DEFAULT = 0.6;
const float A_COLOR_GRADIENT_END_MARK_TEXT_THEME_DEFAULT = 0.7;

const float R_COLOR_GRADIENT_START_TOPBAR_THEME_DEFAULT = 0.3;
const float G_COLOR_GRADIENT_START_TOPBAR_THEME_DEFAULT = 0.3;
const float B_COLOR_GRADIENT_START_TOPBAR_THEME_DEFAULT = 0.4;
const float A_COLOR_GRADIENT_START_TOPBAR_THEME_DEFAULT = 1.0;
const float R_COLOR_GRADIENT_END_TOPBAR_THEME_DEFAULT = 0.2;
const float G_COLOR_GRADIENT_END_TOPBAR_THEME_DEFAULT = 0.2;
const float B_COLOR_GRADIENT_END_TOPBAR_THEME_DEFAULT = 0.3;
const float A_COLOR_GRADIENT_END_TOPBAR_THEME_DEFAULT = 1.0;

const float FOV_DEGREE = 45.0;
const float FACTOR_DRAG = 2.0;
const float FACTOR_VELOCITY = 7.0;
const float MAX_DEGREE_VELOCITY = 720.0;
const float Z_NEAR = 1.0;
const float Z_FAR = 200000.0;
const float FACTOR_LOW_PASS_FILTER = 4.0;